/*
 * @Author: yanbuw1911
 * @Date: 2020-12-07 14:27:12
 * @LastEditTime: 2021-01-08 13:45:24
 * @LastEditors: yanbuw1911
 * @Description: 参考 vxe-grid
 * @FilePath: \client\src\components\SV\SvGrid\props.js
 */
const gridProps = {
  id: String,
  columns: Array,
  data: Array,
  height: [Number, String],
  masHeight: [Number, String],
  autoResize: Boolean,
  syncResize: [Boolean, String, Number],
  resizable: Boolean,
  stripe: Boolean,
  border: [Boolean, String],
  round: Boolean,
  size: String,
  loading: Boolean,
  align: String,
  headerAlign: String,
  footerAlign: String,
  showHeader: Boolean,
  highlightCurrentRow: Boolean,
  highlightHoverRow: Boolean,
  highlightCurrentColumn: Boolean,
  highlightHoverColumn: Boolean,
  highlightCell: Boolean, // draft
  rowClassName: [String, Function],
  cellClassName: [String, Function],
  headerRowClassName: [String, Function],
  headerCellClassName: [String, Function],
  footerRowClassName: [String, Function],
  footerCellClassName: [String, Function],
  showFooter: Boolean,
  footerMethod: Function,
  mergeCells: Array,
  mergeFooterItems: Array,
  showOverflow: [Boolean, String],
  showHeaderOverflow: [Boolean, String],
  showFooterOverflow: [Boolean, String],
  columnKey: Boolean,
  rowKey: Boolean,
  rowId: String,
  keepSource: Boolean,
  columnConfig: Object,
  seqConfig: Object,
  sortConfig: Object,
  filterConfig: Object,
  exportConfig: Object,
  importConfig: Object,
  printConfig: Object,
  radioConfig: Object,
  checkConfig: Object,
  tooltipConfig: Object,
  expandConfig: Object,
  treeConfig: Object,
  menuConfig: Object,
  mouseConfig: Object,
  keyboardConfig: Object,
  editConfig: Object,
  validConfig: Object,
  editRules: Object,
  emptyText: String,
  emptyRender: Object,
  customConfig: Object,
  scrollX: Object,
  scrollY: Object,
  params: Object,
  formConfig: Object,
  toolbarConfig: Object,
  pagerConfig: Object,
  proxyConfig: Object,
  zoomConfig: Object
}

export { gridProps }
